services:
  gitlab:
    image: "gitlab/gitlab-ce:latest"
    container_name: gitlab
    restart: always
    ports:
      - "8082:80"
    environment:
      GITLAB_ROOT_PASSWORD: "zaq1@WSX"
    volumes:
      - ./.volumes/gitlab/config:/etc/gitlab
      - ./.volumes/gitlab/data:/var/opt/gitlab
    networks:
      - bridge_network
    shm_size: "512m"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - 8081:80
      - 50000:50000
    environment:
      JENKINS_OPTS: "--httpPort=80"
    volumes:
      - ./.volumes/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - bridge_network

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - bridge_network

  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yourdb
      MYSQL_PASSWORD: password
    networks:
      - bridge_network

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - bridge_network

volumes:
  db_data:

networks:
  bridge_network:
    driver: bridge